// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-wire-example/cache"
	"go-wire-example/handler"
	"go-wire-example/repo"
	"go-wire-example/service"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	userCache := cache.NewUserCache()
	userRepo := repo.NewUserRepo(userCache)
	userService := service.NewUserService(userRepo)
	userHandler := handler.NewUserHandler(userService)
	productRepo := repo.NewProductRepo()
	productCache := cache.NewProductCache()
	productService := service.NewProductService(productRepo, productCache)
	productHandler := handler.NewProductHandler(productService)
	app := &App{
		UserHandler:    userHandler,
		ProductHandler: productHandler,
	}
	return app, nil
}

// wire.go:

type App struct {
	UserHandler    *handler.UserHandler
	ProductHandler *handler.ProductHandler
}
